AllCops:
  Exclude:
    - 'cici.gemspec'
    - 'vendor/**/*'
    - 'Dangerfile'

Metrics/LineLength:
  Max: 180

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 150  

Documentation:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2